# The following redirects are for generated sdk/sdk-bridge/sdk-govern docs
[[redirects]]
  from = "/sdk"
  to = "/sdk/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/sdk-bridge"
  to = "/sdk-bridge/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/sdk-govern"
  to = "/sdk-govern/index.html"
  status = 301
  force = true
