module.exports = {
  sidebar: [
    {
      type: 'category',
      label: 'Nomad',
      collapsed: false,
      items: [
        'docs',
        {
          type: 'category',
          label: 'Overview',
          items: [
            {
              type: 'doc',
              id: 'overview/what-is-nomad',
              label: 'What is Nomad',
            },
            {
              type: 'doc',
              label: 'Why Nomad',
              id: 'overview/why-nomad',
            },
            {
              type: 'doc',
              id: 'overview/nomad-vs-the-world',
              label: 'Nomad\'s Design'
            }],
        },
      {
          type: 'category',
          label: 'Protocol',
          items: [
            {
              type: 'doc',
              id: 'protocol/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'protocol/messaging',
              label: 'Messaging',
            },
            {
              type: 'doc',
              id: 'protocol/security',
              label: 'Security',
            },
            {
              type: 'doc',
              id: 'protocol/governance',
              label: 'Governance',
            },
            {
              type: 'doc',
              id: 'protocol/agents',
              label: 'Agents',
            }
          ],
        },
      {
          type: 'category',
          label: 'Token Bridge',
          items: [
            {
              type: 'doc',
              id: 'token-bridge/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'token-bridge/nomad-connext',
              label: 'Nomad + Connext',
            },
          ],
        },
      {
          type: 'category',
          label: 'Build on Nomad',
          items: [
            {
              type: 'doc',
              id: 'build/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'build/checklist',
              label: 'Checklist',
            },
            {
              type: 'doc',
              id: 'build/invariants',
              label: 'Nomad Invariants',
            },
            {
              type: 'doc',
              id: 'build/smart-contracts',
              label: 'Smart Contracts',
            },
            {
              type: 'doc',
              id: 'build/agents',
              label: 'Agents',
            },
            {
              type: 'doc',
              id: 'build/sdk',
              label: 'SDK',
            },
          ],
        },
      {
          type: 'category',
          label: 'Operate Agents',
          items: [
            {
              type: 'doc',
              id: 'agents/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'agents/watcher',
              label: 'Watcher',
            },
            {
              type: 'doc',
              id: 'agents/processor',
              label: 'Processor',
            },
            {
              type: 'doc',
              id: 'agents/relayer',
              label: 'Relayer',
            },
            {
              type: 'doc',
              id: 'agents/updater',
              label: 'Updater',
            },
          ],
        },{
          type: 'category',
          label: 'Resources',
          items: [
            {
              type: 'doc',
              id: 'resources/faq',
              label: 'FAQ',
            },
            {
              type: 'doc',
              id: 'resources/audits',
              label: 'Audit',
            },
            {
              type: 'doc',
              id: 'resources/deployed-contracts',
              label: 'Deployed Addresses',
            }]}


    ]
    },{
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
    {
      type: 'autogenerated',
      dirName: 'reference', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
      ]
    }
]
};
