module.exports = {
  sidebar: [
    {
      type: 'category',
      label: 'Nomad',
      collapsed: false,
      items: [
        'docs',
        {
          type: 'category',
          label: 'Overview',
          items: [
            {
              type: 'doc',
              id: 'overview/what-is-nomad',
              label: 'What is Nomad',
            },
            {
              type: 'doc',
              label: 'Why Nomad',
              id: 'overview/why-nomad',
            },
            {
              type: 'doc',
              id: 'overview/nomad-vs-the-world',
              label: 'Nomad\'s design vs others'
            }],
        },
      {
          type: 'category',
          label: 'Nomad Protocol',
          items: [
            {
              type: 'doc',
              id: 'protocol/overview',
              label: 'Overview of the Protocol',
            },
            {
              type: 'doc',
              id: 'protocol/messaging',
              label: 'Messaging',
            },
            {
              type: 'doc',
              id: 'protocol/security',
              label: 'Nomad\'s Security',
            },
            {
              type: 'doc',
              id: 'protocol/governance',
              label: 'Nomad\'s protocol governance',
            },
            {
              type: 'doc',
              id: 'protocol/agents',
              label: 'Offline Agents',
            }
          ],
        },
      {
          type: 'category',
          label: 'Token Bridge',
          items: [
            {
              type: 'doc',
              id: 'token-bridge/overview',
              label: 'What is the token bridge',
            },
            {
              type: 'doc',
              id: 'token-bridge/nomad-connext',
              label: 'Nomad + Connext',
            },
          ],
        },
      {
          type: 'category',
          label: 'Build on Nomad',
          items: [
            {
              type: 'doc',
              id: 'build/overview',
              label: 'What is the token bridge',
            },
            {
              type: 'doc',
              id: 'build/checklist',
              label: 'Everything you need to do',
            },
            {
              type: 'doc',
              id: 'build/invariants',
              label: 'Nomad Invariants',
            },
            {
              type: 'doc',
              id: 'build/smart-contracts',
              label: 'Interact with the Smart Contracts',
            },
            {
              type: 'doc',
              id: 'build/agents',
              label: 'Interact with the Nomad Agents',
            },
            {
              type: 'doc',
              id: 'build/sdk',
              label: 'Nomad SDK',
            },
          ],
        },
      {
          type: 'category',
          label: 'Operate Nomad Agents',
          items: [
            {
              type: 'doc',
              id: 'agents/overview',
              label: 'Running Agents overview',
            },
            {
              type: 'doc',
              id: 'agents/watcher',
              label: 'Run a Watcher',
            },
            {
              type: 'doc',
              id: 'agents/processor',
              label: 'Run a Processor',
            },
            {
              type: 'doc',
              id: 'agents/relayer',
              label: 'Run a Relayer',
            },
            {
              type: 'doc',
              id: 'agents/updater',
              label: 'Run a Relayer',
            },
          ],
        },{
          type: 'category',
          label: 'Resources',
          items: [
            {
              type: 'doc',
              id: 'resources/faq',
              label: 'Nomad FAQ',
            },
            {
              type: 'doc',
              id: 'resources/audits',
              label: 'Nomad Protocol Audit Reports',
            },
            {
              type: 'doc',
              id: 'resources/deployed-contracts',
              label: 'Deployed Smart Contracts',
            }]}


    ]
    },{
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
    {
      type: 'autogenerated',
      dirName: 'reference', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
      ]
    }
]
};
